name: Deploy QR Code Generator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git config
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Check if gh-pages branch exists
      run: git fetch origin gh-pages || git branch gh-pages

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .  # Asegúrate de que sea la carpeta raíz del proyecto, si no, ajusta este valor
        token: ${{ secrets.GITHUB_TOKEN }}
